plcli -a "TaskNameExceedingTwentyFiveCharacters"
plcli -a "TaskFail2" -p "PriorityTooLong"
plcli -a "TaskFail3" -d "2025-03-15_LONG_DUE"
plcli -a "TaskFail4" -n "This note has at least 31 characters total."
plcli -u 1 -t "VeryVeryLongNewNameExceedLimit"
plcli -u 2 -p "IMPOSSIBLELONG"
plcli -u 3 -d "LongDeadline_123"
plcli -u 4 -n "This new note definitely breaks limit!"
plcli -a "TaskFail9" -n "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"  # 31 'A's
plcli -a "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
